name: 'Sample - login'
description: 'Login to to tenant using Office 365 CLI'
inputs:
  ADMIN_USERNAME:  
    description: 'Username (email address) of the admin'
    required: true
  ADMIN_PASSWORD:  
    description: 'Password of the admin'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
