name: Office 365 CLI Login

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Office 365 CLI Login
      uses: ./
      env:
        ADMIN_USERNAME:  ${{ secrets.adminUsername }}
        ADMIN_PASSWORD:  ${{ secrets.adminPassword }}
