name: Office 365 CLI Login (with)

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Office 365 CLI Login
      uses: ./
      with:
        admin_username:  ${{ secrets.adminUsername }}
        addmin_password:  ${{ secrets.adminPassword }}
